### ISSUE TITLE
Pretrained Style Classifier is not Loaded during Training

### ISSUE THREAD

**Issue by XingliangJin** [neu-vi/SMooDi#7]
I find poor performance when retaining the model, the stylized motion can not perform the style. Then I find out that the pretrained style classifier seems not loaded during training. Hope you can check this part.

**Comment by ZiyuGuo24** [comment]
Same issue. Retrain but cannot reproduce the results even with the pre-trained style classifier and style encoder loaded. 

@XingliangJin Have you solved this problem? : )

**Comment by XingliangJin** [comment]
I use the pre-trained Style Encoder from the SMooDi.cpkt (aurthor provided) and frozen the Style Encoder, the results looks good. 

But the aurthor says that the Style Encoder is just a transformer-structure encoder that is trainable (not frozen or load some pretrained parameters) while the controlnet is training. However, with these setting, I can't reproduce the results.
